[project]
name = "chatwithpdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "chromadb",
    "langchain",
    "langchain-chroma",
    "langchain-community",
    "langchain-core",
    "langchain-groq",
    "langchain-huggingface",
    "numpy<2.0.0",
    "pypdf",
    "python-dotenv",
    "sentence-transformers>=3.0.0",
    "streamlit",
    "torch",
]

[tool.uv]
dev-dependencies = []
